// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxyeNxlHte3whXUte8l8ww3hkQC_itrgs',
    appId: '1:445735880114:web:61098a20c7f60bab2650ab',
    messagingSenderId: '445735880114',
    projectId: 'irrigation-597bc',
    authDomain: 'irrigation-597bc.firebaseapp.com',
    storageBucket: 'irrigation-597bc.firebasestorage.app',
    measurementId: 'G-0RCST2ZZD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNAoK5Qb-j2pxLYQw7JLNjiVIZhZPh41s',
    appId: '1:445735880114:android:e82554193b073d752650ab',
    messagingSenderId: '445735880114',
    projectId: 'irrigation-597bc',
    storageBucket: 'irrigation-597bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApvsDKvKz1i1PEm8t1pd4huV7rtG9ADec',
    appId: '1:445735880114:ios:fb27f6cf3f232dc72650ab',
    messagingSenderId: '445735880114',
    projectId: 'irrigation-597bc',
    storageBucket: 'irrigation-597bc.firebasestorage.app',
    iosBundleId: 'com.example.saguia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApvsDKvKz1i1PEm8t1pd4huV7rtG9ADec',
    appId: '1:445735880114:ios:fb27f6cf3f232dc72650ab',
    messagingSenderId: '445735880114',
    projectId: 'irrigation-597bc',
    storageBucket: 'irrigation-597bc.firebasestorage.app',
    iosBundleId: 'com.example.saguia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxyeNxlHte3whXUte8l8ww3hkQC_itrgs',
    appId: '1:445735880114:web:7da496e2245f48572650ab',
    messagingSenderId: '445735880114',
    projectId: 'irrigation-597bc',
    authDomain: 'irrigation-597bc.firebaseapp.com',
    storageBucket: 'irrigation-597bc.firebasestorage.app',
    measurementId: 'G-JZC9D4WWCC',
  );
}
